- direction: 'horizontal'
- name: 'set_pos'
  service: 'dummy_u4'
  column: 0
- name: 'go_pos'
  service: 'dummy_u5'
  column: 0
- name: 'gait_menu'
  service: 'dummy_u1'
  column: 0
- name: 'next'
  service: 'dummy_u8'
  column: 0
- name: 'set_pos_with_av'
  service: 'dummy_b1'
  column: 1
- name: 'send_angle'
  service: 'dummy_b5'
  column: 1
- name: 'robot_menu'
  service: 'dummy_b6'
  column: 1
- name: 'select'
  service: 'dummy_b8'
  column: 1
