hrpsys_gazebo_configuration:
## velocity feedback for joint control, use parameter gains/joint_name/p_v
# use_velocity_feedback: true
## synchronized hrpsys and gazebo
# use_synchronized_command: false
# name of robot (using for namespace)
  robotname: JVRC
# joint_id (order) conversion from gazebo to hrpsys, joint_id_list[gazebo_id] := hrpsys_id
  joint_id_list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]
# joints list used in gazebo, sizeof(joint_id_list) == sizeof(joints)
  joints:
    - R_HIP_P
    - R_HIP_R
    - R_HIP_Y
    - R_KNEE
    - R_ANKLE_R
    - R_ANKLE_P
    - L_HIP_P
    - L_HIP_R
    - L_HIP_Y
    - L_KNEE
    - L_ANKLE_R
    - L_ANKLE_P
    - WAIST_Y
    - WAIST_P
    - WAIST_R
    - NECK_Y
    - NECK_R
    - NECK_P
    - R_SHOULDER_P
    - R_SHOULDER_R
    - R_SHOULDER_Y
    - R_ELBOW_P
    - R_ELBOW_Y
    - R_WRIST_R
    - R_WRIST_Y
    - R_UTHUMB
    - R_LTHUMB
    - R_UINDEX
    - R_LINDEX
    - R_ULITTLE
    - R_LLITTLE
    - L_SHOULDER_P
    - L_SHOULDER_R
    - L_SHOULDER_Y
    - L_ELBOW_P
    - L_ELBOW_Y
    - L_WRIST_R
    - L_WRIST_Y
    - L_UTHUMB
    - L_LTHUMB
    - L_UINDEX
    - L_LINDEX
    - L_ULITTLE
    - L_LLITTLE   
  gains:
    R_HIP_P:      {p: 2000, d:  20.0, i: 0.0, i_clamp: 0.0} 
    R_HIP_R:      {p: 2000, d:  20.0, i: 0.0, i_clamp: 0.0}
    R_HIP_Y:      {p: 2000, d:  20.0, i: 0.0, i_clamp: 0.0}
    R_KNEE:       {p: 2000, d:  20.0, i: 0.0, i_clamp: 0.0}
    R_ANKLE_R:    {p: 2000, d:  20.0, i: 0.0, i_clamp: 0.0}
    R_ANKLE_P:    {p: 2000, d:  20.0, i: 0.0, i_clamp: 0.0}
    L_HIP_P:      {p: 2000, d:  20.0, i: 0.0, i_clamp: 0.0}
    L_HIP_R:      {p: 2000, d:  20.0, i: 0.0, i_clamp: 0.0}
    L_HIP_Y:      {p: 2000, d:  20.0, i: 0.0, i_clamp: 0.0}
    L_KNEE:       {p: 2000, d:  20.0, i: 0.0, i_clamp: 0.0}
    L_ANKLE_R:    {p: 2000, d:  20.0, i: 0.0, i_clamp: 0.0}
    L_ANKLE_P:    {p: 2000, d:  20.0, i: 0.0, i_clamp: 0.0}
    WAIST_Y:      {p: 400, d:  1.0, i: 0.0, i_clamp: 0.0}
    WAIST_P:      {p: 400, d:  1.0, i: 0.0, i_clamp: 0.0}
    WAIST_R:      {p: 400, d:  1.0, i: 0.0, i_clamp: 0.0}
    NECK_Y:       {p: 100, d:  1.0, i: 0.0, i_clamp: 0.0}
    NECK_R:       {p: 100, d:  1.0, i: 0.0, i_clamp: 0.0}
    NECK_P:       {p: 100, d:  1.0, i: 0.0, i_clamp: 0.0}
    R_SHOULDER_P: {p: 200, d:  2.0, i: 0.0, i_clamp: 0.0}
    R_SHOULDER_R: {p: 200, d:  2.0, i: 0.0, i_clamp: 0.0}
    R_SHOULDER_Y: {p: 200, d:  2.0, i: 0.0, i_clamp: 0.0}
    R_ELBOW_P:    {p: 200, d:  2.0, i: 0.0, i_clamp: 0.0}
    R_ELBOW_Y:    {p: 200, d:  2.0, i: 0.0, i_clamp: 0.0}
    R_WRIST_R:    {p: 200, d:  2.0, i: 0.0, i_clamp: 0.0}
    R_WRIST_Y:    {p: 200, d:  2.0, i: 0.0, i_clamp: 0.0}
    R_UTHUMB:     {p: 30, d:  0.1, i: 0.0, i_clamp: 0.0}
    R_LTHUMB:     {p: 30, d:  0.1, i: 0.0, i_clamp: 0.0}
    R_UINDEX:     {p: 30, d:  0.1, i: 0.0, i_clamp: 0.0}
    R_LINDEX:     {p: 30, d:  0.1, i: 0.0, i_clamp: 0.0}
    R_ULITTLE:    {p: 30, d:  0.1, i: 0.0, i_clamp: 0.0}
    R_LLITTLE:    {p: 30, d:  0.1, i: 0.0, i_clamp: 0.0}
    L_SHOULDER_P: {p: 200, d:  2.0, i: 0.0, i_clamp: 0.0}
    L_SHOULDER_R: {p: 200, d:  2.0, i: 0.0, i_clamp: 0.0}
    L_SHOULDER_Y: {p: 200, d:  2.0, i: 0.0, i_clamp: 0.0}
    L_ELBOW_P:    {p: 200, d:  2.0, i: 0.0, i_clamp: 0.0}
    L_ELBOW_Y:    {p: 200, d:  2.0, i: 0.0, i_clamp: 0.0}
    L_WRIST_R:    {p: 200, d:  2.0, i: 0.0, i_clamp: 0.0}
    L_WRIST_Y:    {p: 200, d:  2.0, i: 0.0, i_clamp: 0.0}
    L_UTHUMB:     {p: 30, d:  0.1, i: 0.0, i_clamp: 0.0}
    L_LTHUMB:     {p: 30, d:  0.1, i: 0.0, i_clamp: 0.0}
    L_UINDEX:     {p: 30, d:  0.1, i: 0.0, i_clamp: 0.0}
    L_LINDEX:     {p: 30, d:  0.1, i: 0.0, i_clamp: 0.0}
    L_ULITTLE:    {p: 30, d:  0.1, i: 0.0, i_clamp: 0.0}
    L_LLITTLE:    {p: 30, d:  0.1, i: 0.0, i_clamp: 0.0}
  force_torque_sensors:
    - rfsensor
    - lfsensor
    - rhsensor
    - lhsensor
  force_torque_sensors_config:
## TODO: add translation and rotation
    lfsensor: {joint_name: 'LLEG_JOINT5', frame_id: 'LLEG_LINK5', translation: [0, 0, -0.069], rotation: [0, 0, 1, 3.14159]}
    rfsensor: {joint_name: 'RLEG_JOINT5', frame_id: 'RLEG_LINK5', translation: [0, 0, -0.069], rotation: [0, 0, 1, 3.14159]}
    lhsensor: {joint_name: 'LARM_JOINT7', frame_id: 'LARM_LINK7', translation: [0, 0, -0.069], rotation: [-0.382683, -0.92388, 0, 3.14159]}
    rhsensor: {joint_name: 'RARM_JOINT7', frame_id: 'RARM_LINK7', translation: [0, 0, -0.069], rotation: [-0.382683, -0.92388, 0, 3.14159]}
#   imu_sensors:
#     - imu_sensor0
#   imu_sensors_config:
# ## TODO: add translation and rotation
#      imu_sensor0: {ros_name: 'waist_imu', link_name: 'BODY', frame_id: 'BODY'}
#   range_sensors:
#     - imu_sensor0
#   rage_sensors_config:

#   camera_sensors:
#     - imu_sensor0
#   camera_sensors_config:

#   depth_camera_sensors:
#     - imu_sensor0
#   depth_sensors_config:
