### sample yaml
HRP2JSKNTS:
  name: 'HRP2JSKNTS'
  type: 'robot'
  file: '$(find hrp2_models)/HRP2JSKNTS_WITH_3HAND/HRP2JSKNTSmain_bush.wrl'
  translation: [0, 0, 0.65]
  rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
  joint_angles: [0.0, 0.0, -0.453786, 0.872665, -0.418879, 0.0, 0.0,
                 0.0, 0.0, -0.453786, 0.872665, -0.418879, 0.0, 0.0,
                 0.0, 0.0, 0.0, 0.0,
                 0.174533, -0.174533, 0.0, -0.436332, 0.0, 0.0, -0.174533, 0.261799,
                 0.174533, 0.174533, 0.0, -0.436332, 0.0, 0.0, -0.174533, -0.261799,
                 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  body_rtc:
    - name: 'HRP2JSKNTS(Robot)0'
      module: '$(find hrpsys_choreonoid)/lib/RobotHardware_choreonoid.so'
      config: '$(find hrpsys_choreonoid_tutorials)/config/BodyRTC_HRP2JSKNTS.RH.conf'
      rate: 250
    - name: 'HRP3HAND(Robot)0'
      module: '$(find hrpsys_choreonoid)/lib/HRP3HandController_choreonoid.so'
      config: '$(find hrpsys_choreonoid_tutorials)/config/BodyRTC_HRP2JSKNTS.HC.conf'
      rate: 250
  # vision:
  #   body: 'JAXON_RED'
  #   namelist: 'HEAD_LEFT_CAMERA, HEAD_RIGHT_CAMERA, HEAD_RANGE'
obj2:
  name: 'VIS_FLOOR'
  file: '$(find jvrc_models)/models/visible_floor.wrl'
  translation: [0, 0, -0.1]
  rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
sci1:
  type: 'script'
  file: '$(find hrpsys_choreonoid)/scripts/ros_service_server.py'
start_simulation: True
#robot:
#  name: ''
#  type: 'robot'
#  file: ''
#  translation: []
#  rotation: [[], [], []]
#  joint_angles: []
#  body_rtc:
#    name:
#    module:
#    config:
#    rate:
#  vision:
#    body:
#    namelist:
#sci:
#  name: ''
#  type: 'script'
#  file: ''
