bush:
  springT: 3.3e5
  dampingT: 3.3e2
  springR: 1.0e3
  dampingR: 1.0

armbush:
  springT: 1.0e5
  dampingT: 1.0e3
  springR: 3.0e2
  dampingR: 3.0

tilt_laser:
  TILT_UPPER_BOUND: 1.35
  TILT_POSITIVE_SPEED: 1.0
  TILT_LOWER_BOUND: -0.7
  TILT_NEGATIVE_SPEED: -1.0
